spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres   # or your DB name, e.g., scheduler
    driver-class-name: org.postgresql.Driver
    username: cnk
    password: cnk
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
